require("kaesouza.keymaps")
require("kaesouza.options")
require("kaesouza.plugins")
require("kaesouza.commands")
require("plugins.telescope")
require("plugins.treesitter")
require("lsp")
print("[Hello master, Kaliel]")
print("[From NVIM]")
