require("kaesouza.keymaps")
require("kaesouza.options")
require("kaesouza.plugins")
require("kaesouza.commands")
require("plugins.telescope")
require("plugins.treesitter")
print("Hello master Kaliel")
